version: '3.3'
services:
    athens-backend:
        ports:
            - '13337:1337'
        volumes:
            - '/root/athens/db/athens-backend:/tmp/athens'
        image: 'erulabs/athens-backend:latest'
